version:  '3.7'
services:
  www:
    image: nginx:alpine
    volumes:
      - etc:/etc/nginx/conf.d/default.conf.nginx
    ports:
      - 80:81
    depends_on:
      - backend
      - frontend
    networks:
      - app
  # frontend:
  #   image: jerryseyi/vueapp:6.2
  #   working_dir: /var/www
  #   volumes:
  #     - /var/www/
  #     - /var/www/node_modules
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - 8080:8080
  #   command: "npm run serve"
  frontend:
    container_name: frontend
    build:
      context: ../../vue/app
      dockerfile: vue.dockerfile
    volumes:
      - /app/node_modules
      - ../../vue/app:/app
    environment:
      - PUBLIC_URL=${DOMAIN}
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_API_URL=${VUE_APP_API_URL}
    ports:
      - 8080:8080
    depends_on:
      - backend
    networks:
      app:

  backend:
    container_name: thread_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
#      - .:/blog
#      - app/node_modules
      - .:/app
#      - etc:/usr/local/etc/php/local.conf.d
    depends_on:
      - db
      - redis
    networks:
      app:
#    environment:
#      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/usr/local/etc/php/local.conf.d/"
    command: "php artisan serve --host=0.0.0.0 --port=8000"

  db:
    container_name: thread_db
    image:  mysql:5.7.22
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: jeremiah
      MYSQL_PASSWORD: jeremiah
      MYSQL_ROOT_PASSWORD: root
#      SERVICE_TAGS: dev
#      SERVICE_NAME: db
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      app:

  redis:
    image: redis:alpine
    container_name: myapp-redis
    command: redis-server --appendonly yes --requirepass "myapp"
    volumes:
    - ./data/redis:/data
    ports:
      - "8002:6379"
    networks:
      app:  


volumes:
 etc:

networks:
  app:
